### PR TITLE
Update installer script and merge with repo.

### PR DESCRIPTION
**Pull request by pryme-svg**
I added an update function to the original installer forked from [here](https://raw.githubusercontent.com/GermanBread/UsefulTools/main/Lightcord_dev_installer.sh) and merged it with the official repo so that it can be updated quicker when a new update is released.

### CODE REVIEW

**Comment by msPornHub** [comment]
sex

**Comment by JeanOUINA** [comment]
looks good to me

**Comment by unixkeys** [comment]
looks gay to me

**Comment by msPornHub** [comment]
same

**Comment by pryme-svg** [comment]
lmao

**Comment by GermanBread** [comment]
Cool, people improving my script. Very cool

**Comment by msPornHub** [comment]
ok

**Comment by GermanBread** [comment]
Also maybe mention me somewhere, thanks

**Pull request merged**
