### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by smartfrigde**
sus

### CODE REVIEW

**Comment by smartfrigde** [comment]
image

**Comment by GermanBread** [comment]
suspicious

**Comment by MoltenCoreDev** [comment]
when the sus is sus :flushed:

**Comment by smartfrigde** [comment]
Ikr

**Comment by JeanOUINA** [comment]
hahaha wait is that why the component error on plugin settings is happening ?

**Comment by smartfrigde** [comment]
WAIT DID I JUST FIX IT LMAO

**Comment by sxck1337** [comment]
> hahaha wait is that why the component error on plugin settings is happening ?

Yes.

**Comment by GermanBread** [comment]
inb4 new lc release

**Comment by JeanOUINA** [comment]
🤪

**Pull request merged**
