### PR TITLE
Delete pluginCertifier.js

### PR DESCRIPTION
**Pull request by SomeAspy**
because its trash. just removing this may or may not work. but either way, kill it

### CODE REVIEW

**Comment by pryme-svg** [comment]
you would need to patch these lines too 
image

**Review by JeanOUINA — CHANGES_REQUESTED** [review]
Just removing the file wouldn't remove the feature entirely, it needs other changes in other files as well.

**Comment by SomeAspy** [comment]
Yea I realize that, I just want it gone ASAP, whihc is why I made this, as it doesnt work properly

**Comment by pryme-svg** [comment]
You can disable it

**Comment by papycochon** [comment]
> Yea I realize that, I just want it gone ASAP, whihc is why I made this, as it doesnt work properly Will look into this

it's gone in rewrite 🧓

**Pull request closed without merging**
