### PR TITLE
fish bad, none of my homies use fish

### PR DESCRIPTION
**Pull request by GermanBread**

### CODE REVIEW

**Comment by GermanBread** [comment]
e

**Comment by smartfrigde** [comment]
e

**Comment by smartfrigde** [comment]
wat

**Comment by vbajs** [comment]
Fish bad
Zsh ok
Bash superior

**Comment by smartfrigde** [comment]
why would name something fish

**Comment by GermanBread** [comment]
because

f i s h

**Comment by GermanBread** [comment]
idk it's a bad shell

**Pull request merged**
